[package]
name = "internment"
version = "0.1.0"
edition = "2018"

[features]
default = []
flatbuf = ["differential_datalog/flatbuf","ddlog_rt/flatbuf", "ddlog_std/flatbuf", "ddlog_bigint/flatbuf"]
c_api = ["differential_datalog/c_api","ddlog_rt/c_api", "ddlog_std/c_api", "ddlog_bigint/c_api"]

[dependencies]
differential_datalog = { path = "../../differential_datalog" }
ddlog_profiler = { path = "../../ddlog_profiler" }
ddlog_derive = { path = "../../ddlog_derive" }
abomonation = "0.7"
ordered-float = { version = "2.0.0", features = ["serde"] }
fnv = "1.0.2"
twox-hash = "1.6.0"
once_cell = "1.4.1"
libc = "0.2"
time = { version = "0.2", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
num = "0.3"
erased-serde = "0.3"
differential-dataflow = { git = "https://github.com/ddlog-dev/differential-dataflow", branch = "ddlog-4" }
timely = { git = "https://github.com/ddlog-dev/timely-dataflow", branch = "ddlog-4",  default-features = false }

ddlog_rt = { path = "../ddlog_rt" }
ddlog_std = { path = "../ddlog_std" }
ddlog_bigint = { path = "../ddlog_bigint" }

[lib]
name = "internment"
path = "internment.rs"
[dependencies.internment]
version="0.5.4"
features=["arc"]
