[workspace]
members = [
    "crates/core",
    "crates/ir", 
    "crates/language",
    "crates/frontend",
    "crates/backend",
    "crates/traverse-cli",
    "crates/compiler",
    "crates/tree-sitter-traverse"
]

# exclude workspae members 
exclude = [
    "ri/solidity_ddlog",
]


