priorities:
  participants: 100
  flow: 90
path_attributes:
  participants: path
  flow: ce_id_path
value_attributes:
  participants: val
  flow: val
default_path_attribute: path
default_value_attribute: val
default_priority: 0
pool_shape: sequenceDiagram
bucket_relations:
  participants:
  - relation_name: EmitMermaidLineCallerParticipantLine
    priority: 100
  - relation_name: EmitMermaidLineCalleeParticipantLine
    priority: 90
  - relation_name: EmitMermaidLineContractParticipantLine
    priority: 90
  flow:
  - relation_name: EmitMermaidLineSignalLine
    priority: 100
  - relation_name: EmitMermaidLineActivateLine
    priority: 90
  - relation_name: EmitMermaidLineReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraSignalLine
    priority: 100
  - relation_name: EmitMermaidLineIntraSignalLineNoReturn
    priority: 100
  - relation_name: EmitMermaidLineIntraActivateLine
    priority: 90
  - relation_name: EmitMermaidLineIntraActivateLineNoReturn
    priority: 90
  - relation_name: EmitMermaidLineIntraReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineIntraDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraDeactivateLineNoReturn
    priority: 70
relation_to_bucket:
  EmitMermaidLineIntraActivateLine: flow
  EmitMermaidLineDeactivateLine: flow
  EmitMermaidLineContractParticipantLine: participants
  EmitMermaidLineIntraDeactivateLine: flow
  EmitMermaidLineIntraActivateLineNoReturn: flow
  EmitMermaidLineReturnSignalLine: flow
  EmitMermaidLineIntraReturnSignalLine: flow
  EmitMermaidLineIntraDeactivateLineNoReturn: flow
  EmitMermaidLineIntraSignalLineNoReturn: flow
  EmitMermaidLineSignalLine: flow
  EmitMermaidLineCallerParticipantLine: participants
  EmitMermaidLineCalleeParticipantLine: participants
  EmitMermaidLineActivateLine: flow
  EmitMermaidLineIntraSignalLine: flow
relation_priorities:
  EmitMermaidLineIntraActivateLineNoReturn: 90
  EmitMermaidLineCalleeParticipantLine: 90
  EmitMermaidLineIntraReturnSignalLine: 80
  EmitMermaidLineDeactivateLine: 70
  EmitMermaidLineActivateLine: 90
  EmitMermaidLineContractParticipantLine: 90
  EmitMermaidLineReturnSignalLine: 80
  EmitMermaidLineIntraDeactivateLine: 70
  EmitMermaidLineIntraDeactivateLineNoReturn: 70
  EmitMermaidLineIntraSignalLineNoReturn: 100
  EmitMermaidLineCallerParticipantLine: 100
  EmitMermaidLineSignalLine: 100
  EmitMermaidLineIntraSignalLine: 100
  EmitMermaidLineIntraActivateLine: 90
