priorities:
  flow: 90
  participants: 100
  mock-actor-flows: 95
path_attributes:
  mock-actor-flows: mock_actor_func_id_path
  flow: intra_ce_no_return_id_path
  participants: path
value_attributes:
  flow: val
  mock-actor-flows: val
  participants: val
default_path_attribute: path
default_value_attribute: val
default_priority: 0
pool_shape: sequenceDiagram
bucket_relations:
  flow:
  - relation_name: EmitMermaidLineSignalLine
    priority: 100
  - relation_name: EmitMermaidLineActivateLine
    priority: 90
  - relation_name: EmitMermaidLineReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraSignalLine
    priority: 100
  - relation_name: EmitMermaidLineIntraSignalLineNoReturn
    priority: 100
  - relation_name: EmitMermaidLineIntraActivateLine
    priority: 90
  - relation_name: EmitMermaidLineIntraActivateLineNoReturn
    priority: 90
  - relation_name: EmitMermaidLineIntraReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineIntraDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraDeactivateLineNoReturn
    priority: 70
  participants:
  - relation_name: EmitMermaidLineMockActorLine
    priority: 100
  - relation_name: EmitMermaidLineMockActorParticipantLine
    priority: 99
  - relation_name: EmitMermaidLineCallerParticipantLine
    priority: 95
  - relation_name: EmitMermaidLineCalleeParticipantLine
    priority: 90
  - relation_name: EmitMermaidLineContractParticipantLine
    priority: 90
  mock-actor-flows:
  - relation_name: EmitMermaidLineMockActorSignalLine
    priority: 100
relation_to_bucket:
  EmitMermaidLineDeactivateLine: flow
  EmitMermaidLineIntraActivateLine: flow
  EmitMermaidLineSignalLine: flow
  EmitMermaidLineCalleeParticipantLine: participants
  EmitMermaidLineIntraReturnSignalLine: flow
  EmitMermaidLineIntraSignalLineNoReturn: flow
  EmitMermaidLineActivateLine: flow
  EmitMermaidLineIntraActivateLineNoReturn: flow
  EmitMermaidLineIntraSignalLine: flow
  EmitMermaidLineReturnSignalLine: flow
  EmitMermaidLineMockActorLine: participants
  EmitMermaidLineCallerParticipantLine: participants
  EmitMermaidLineIntraDeactivateLine: flow
  EmitMermaidLineMockActorSignalLine: mock-actor-flows
  EmitMermaidLineIntraDeactivateLineNoReturn: flow
  EmitMermaidLineContractParticipantLine: participants
  EmitMermaidLineMockActorParticipantLine: participants
relation_priorities:
  EmitMermaidLineMockActorLine: 100
  EmitMermaidLineDeactivateLine: 70
  EmitMermaidLineIntraReturnSignalLine: 80
  EmitMermaidLineMockActorSignalLine: 100
  EmitMermaidLineCallerParticipantLine: 95
  EmitMermaidLineIntraSignalLineNoReturn: 100
  EmitMermaidLineIntraDeactivateLineNoReturn: 70
  EmitMermaidLineContractParticipantLine: 90
  EmitMermaidLineReturnSignalLine: 80
  EmitMermaidLineIntraDeactivateLine: 70
  EmitMermaidLineCalleeParticipantLine: 90
  EmitMermaidLineSignalLine: 100
  EmitMermaidLineIntraSignalLine: 100
  EmitMermaidLineIntraActivateLineNoReturn: 90
  EmitMermaidLineMockActorParticipantLine: 99
  EmitMermaidLineIntraActivateLine: 90
  EmitMermaidLineActivateLine: 90
streams: {}
