priorities:
  participants: 100
  mock-actor-flows: 95
  flow: 90
path_attributes:
  mock-actor-flows: mock_actor_func_id_path
  flow: intra_ce_no_return_id_path
  participants: path
value_attributes:
  mock-actor-flows: val
  flow: val
  participants: val
default_path_attribute: path
default_value_attribute: val
default_priority: 0
pool_shape: sequenceDiagram
bucket_relations:
  flow:
  - relation_name: EmitMermaidLineSignalLine
    priority: 100
  - relation_name: EmitMermaidLineActivateLine
    priority: 90
  - relation_name: EmitMermaidLineReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraSignalLine
    priority: 100
  - relation_name: EmitMermaidLineIntraSignalLineNoReturn
    priority: 100
  - relation_name: EmitMermaidLineIntraActivateLine
    priority: 90
  - relation_name: EmitMermaidLineIntraActivateLineNoReturn
    priority: 90
  - relation_name: EmitMermaidLineIntraReturnSignalLine
    priority: 80
  - relation_name: EmitMermaidLineIntraDeactivateLine
    priority: 70
  - relation_name: EmitMermaidLineIntraDeactivateLineNoReturn
    priority: 70
  mock-actor-flows:
  - relation_name: EmitMermaidLineMockActorSignalLine
    priority: 100
  participants:
  - relation_name: EmitMermaidLineMockActorLine
    priority: 100
  - relation_name: EmitMermaidLineMockActorParticipantLine
    priority: 99
  - relation_name: EmitMermaidLineCallerParticipantLine
    priority: 95
  - relation_name: EmitMermaidLineCalleeParticipantLine
    priority: 90
  - relation_name: EmitMermaidLineContractParticipantLine
    priority: 90
relation_to_bucket:
  EmitMermaidLineMockActorSignalLine: mock-actor-flows
  EmitMermaidLineCallerParticipantLine: participants
  EmitMermaidLineIntraSignalLine: flow
  EmitMermaidLineIntraActivateLine: flow
  EmitMermaidLineIntraSignalLineNoReturn: flow
  EmitMermaidLineIntraActivateLineNoReturn: flow
  EmitMermaidLineIntraDeactivateLine: flow
  EmitMermaidLineSignalLine: flow
  EmitMermaidLineReturnSignalLine: flow
  EmitMermaidLineMockActorLine: participants
  EmitMermaidLineIntraReturnSignalLine: flow
  EmitMermaidLineMockActorParticipantLine: participants
  EmitMermaidLineActivateLine: flow
  EmitMermaidLineDeactivateLine: flow
  EmitMermaidLineIntraDeactivateLineNoReturn: flow
  EmitMermaidLineCalleeParticipantLine: participants
  EmitMermaidLineContractParticipantLine: participants
relation_priorities:
  EmitMermaidLineCalleeParticipantLine: 90
  EmitMermaidLineSignalLine: 100
  EmitMermaidLineActivateLine: 90
  EmitMermaidLineMockActorLine: 100
  EmitMermaidLineIntraActivateLineNoReturn: 90
  EmitMermaidLineDeactivateLine: 70
  EmitMermaidLineIntraDeactivateLine: 70
  EmitMermaidLineIntraSignalLineNoReturn: 100
  EmitMermaidLineIntraActivateLine: 90
  EmitMermaidLineMockActorSignalLine: 100
  EmitMermaidLineContractParticipantLine: 90
  EmitMermaidLineCallerParticipantLine: 95
  EmitMermaidLineIntraSignalLine: 100
  EmitMermaidLineReturnSignalLine: 80
  EmitMermaidLineMockActorParticipantLine: 99
  EmitMermaidLineIntraDeactivateLineNoReturn: 70
  EmitMermaidLineIntraReturnSignalLine: 80
streams:
  actor-flow-stream:
  - mock-actor-flows
  - flow
stream_shapes:
  actor-flow-stream: sequenceDiagram
